accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^$', views.profile, name="profile"),
    re_path(r'^signup/$', views.signupView, name="signup"),
    re_path(r'^login/$', views.loginView, name="login"),
    re_path(r'^logout/$', views.logoutView, name="logout"),
]

articles/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'articles'

urlpatterns = [
    re_path(r'^$', views.articles_list, name="list"),
    re_path(r'^create/$', views.articles_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.articles_detail, name="detail"),
]

urlpatterns += staticfiles_urlpatterns()

challenges/urls.py
from django.urls import path, re_path
from . import views

app_name = 'challenges'

urlpatterns = [
    re_path(r'^$', views.challengesView, name="challenge"),
]

coders/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^articles/', include('articles.urls')),
    re_path(r'^challenges/', include('challenges.urls')),
    re_path(r'^$', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    content = models.TextField()
    imageSmall = models.ImageField(default='defaultImageSmall.png', upload_to='articlesPictures/articlesSmall', blank=True)
    image = models.ImageField(default='defaultImage.jpg', upload_to='articlesPictures/articlesImages', blank=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:250] + '...'

challenges/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Add a valid email adress')
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.firstName = self.cleaned_data['first_name']
        user.lastName = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = (
            'title',
            'slug',
            'content',
            'imageSmall',
            'image',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from accounts.forms import RegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def signupView(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('/accounts/signup/')
    else:
        form = RegistrationForm()
    args = {'form': form}
    return render(request, 'accounts/signup.html', args)

def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    args = {'form': form}
    return render(request, 'accounts/login.html', args)

def logoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

@login_required(login_url="/accounts/login/")
def profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/account.html', args)

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Articles
from . import forms
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
def articles_list(request):
    articles = Articles.objects.all().order_by('-date')
    args = {'articles': articles}
    return render(request, 'articles/articleList.html', args)

def articles_detail(request, slug):
    #return HttpResponse(slug)
    article = Articles.objects.get(slug=slug)
    args = {'article': article}
    return render(request, 'articles/articleDetail.html', args)

@login_required(login_url="/accounts/login/")
def articles_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('/articles/')
    else:
        form = forms.CreateArticle()
    args = {'form' : form}
    return render(request, 'articles/articleCreate.html', args)

challenges/views.py
from django.shortcuts import render, redirect


# Create your views here.
def challengesView(request):
    return render(request, 'challenges/challenges.html')

coders/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

accounts/templates/accounts/account.html
{% extends 'baseTemplate.html' %}

{% block content %}

<div class="container" style="height: 80vh;">
    <div class="row my-5">
        <div class="list-group col-12 col-lg-3 p-2">
            <a href="#" class="list-group-item list-group-item-action active text-uppercase">HI
                {{user.username}}!</a>
            <a href="{% url 'articles:create' %}" class="list-group-item list-group-item-action">ADD ARTICLE</a>
            <a href="#" class="list-group-item list-group-item-action">CHANGE PROFIL PICTURE</a>
            <form action="{% url 'accounts:logout' %}" method="post" style="margin-top: -1px;">
                {% csrf_token %}
                <button class="list-group-item list-group-item-action">LOG OUT</button>
            </form>

        </div>
        <div class="list-group col-12 col-lg-9 p-2">
            <span class="list-group-item active text-uppercase">ACCOUNT DETAILS</span>
            <div class="list-group-item d-flex account-details-img">
                <img src="https://pbs.twimg.com/media/ECDNFYSWwAANZOE.jpg" class="rounded" width="128px" height="128px">
                <div class="account-details px-2">
                    <h3 class="py-1">{{user.first_name}} {{user.last_name}}</h3>
                    <medium>{{user.email}}</medium>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'formTemplate.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center" style="margin-top: 20vh;">
        <div class="card mx-3" style="background-color: #393e46; width: 30rem;">
            <div class="card-title mt-3 align-self-center px-5">
                <a href="{% url 'home' %}"><img src="/media/snakeWhite.png" class="img-fluid" width="64px"
                        height="64px"></a>
            </div>
            <div class="card-body px-5">
                <form class="form-group" action="{% url 'accounts:login' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-danger btn-block my-2">LOG IN</button>
                </form>
                <p class="mt-3 text-center">Dont have an account? <a href="{% url 'accounts:signup' %}">Register</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'formTemplate.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center my-2">
        <div class="card mx-3" style="background-color: #393e46;">
            <div class="card-title mt-3 align-self-center px-5">
                <a href="{% url 'home' %}"><img src="/media/snakeWhite.png" class="img-fluid" width="64px"
                        height="64px"></a>
            </div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success mx-5 my-3">{{ message }}</div>
            {% endfor %}
            {% endif %}
            <div class="card-body px-5">
                <form class="form-group" action="/accounts/signup/" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br />
                    <button type="submit" class="btn btn-danger btn-block">REGISTER</button>
                </form>
                <p class="mt-3 text-center">Do you have an account? <a href="{% url 'accounts:login' %}">Login</a>
                </p>

            </div>
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/articleCreate.html
{% extends 'baseTemplate.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row my-5">
        <div class="list-group col-12 col-lg-3 p-2">
            <span href="#" class="list-group-item list-group-item-action active text-uppercase">HI
                {{user.username}}!</span>
            <a href="/accounts/" class="list-group-item list-group-item-action">BACK TO YOUR
                ACCOUNT</a>
            <a href="{% url 'articles:list' %}" class="list-group-item list-group-item-action">BACK TO NEWS</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Lorem ipsum dolor sit amet consectetur,
                adipisicing elit. A eaque impedit sequi laborum architecto natus culpa ex quisquam beatae repellendus?
                Tenetur possimus, dolor, placeat modi distinctio officiis corrupti ea quos nulla ipsum nesciunt eius
                dicta.</a>
        </div>
        <div class="create-article col-12 col-lg-9 p-2">
            <div class="card">
                <div class="card-header bg-danger text-white text-center">ADD ARTICLE</div>
                <div class="card-body">
                    <form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-danger btn-block">CREATE</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/articleDetail.html
{% extends 'baseTemplate.html' %}

{% block content %}
<div class="article-detail text-dark">
  <div class=" article-detail-img">
  </div>
  <article>
    <div class="container" style="padding-bottom: 100px;">
      <header>
        <h1 class="text-uppercase py-2">{{article.title}}</h1>
      </header>
      <div class="article-detail-metadata">
        <a class="mr-2" href="#">{{article.author}}</a>
        <medium class="text-muted">{{article.date|date:"F d, Y"}}</medium>
      </div>
      <div class="article-detail-body py-5">
        <p class="text-justify">{{article.content}}</p>
      </div>
    </div>
  </article>
</div>
{% endblock %}

articles/templates/articles/articleList.html
{% extends 'baseTemplate.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="articles col-sm-12 col-lg-9">
      <article class="media m-2">
        <ul class="list-unstyled">
          {% for article in articles %}
          <li class="media">
            <img class="mr-3 rounded align-self-center d-none d-lg-block" src="{{article.imageSmall.url}}" alt="..."
              width="128px" height="128px">
            <div class="media-body">
              <a class="article-title mt-0 mb-1"
                href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a>
              <p class="py-2 text-justify">{{article.snippet}}</p>
              <div class="media-metadata">
                <a class="mr-2" href="#">{{article.author}}</a>
                <medium class="text-muted">{{article.date|date:"F d, Y"}}</medium>
              </div>
            </div>

          </li>
          {% endfor %}
        </ul>
      </article>
    </div>
    <aside class="col-sm-12 col-lg-3 my-3">
      <div class="list-group py-2">
        <span class="list-group-item list-group-item-action active text-uppercase">SEARCH</span>
        <div class="list-group-item">
          <form class="form-inline">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" style="width:100%;">
            <button class="btn btn-danger btn-block my-2" type="submit">SEARCH</button>
          </form>
        </div>
      </div>
      {% if user.is_authenticated %}
      <div class="list-group py-2">
        <span class="list-group-item list-group-item-action active">ARTICLES MENU</span>
        <a href="{% url 'articles:create' %}" class="list-group-item list-group-item-action">ADD ARTICLE</a>
        <a href="#" class="list-group-item list-group-item-action">DELETE ARTICLE</a>
      </div>
      {% endif %}
      <div class="list-group py-2">
        <a href="#" class="list-group-item list-group-item-action active text-uppercase">RECENTLY ADDED</a>
        {% for article in articles %}
        <a class="list-group-item list-group-item-action"
          href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a>
        {% endfor %}
      </div>
    </aside>
  </div>
</div>
{% endblock %}

templates/baseTemplate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Coders</title>
  <link rel="icon" type="image/png" href="https://i.imgur.com/Nxcu8gm.png">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <style type="text/css">
  .homepage-box {
    background: url('/media/homepageImage.jpg') no-repeat center;
    background-size: cover;
    background-attachment: fixed;
    height: 90vh;
  }

  .homepage-box-text {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
  }

  .article-detail-img {
    background: url('{{article.image.url}}') no-repeat center;
    background-size: cover;
    height: 45vh;
  }

  .article-detail article {
    background-color: #eeeeee;
    height: 100%;
  }

  .article-detail-metadata a {
    font-size: medium;
  }

  .account-content {
    border: 1px solid rgba(0, 0, 0, .125);
  }

  .list-group-item.active {
    z-index: 2;
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
  }

  .articles article .media {
    border: 1px solid rgba(0, 0, 0, .125);
    margin: 1rem;
    padding: 1rem;
    background-color: #ffffff;
  }

  .articles article .media .article-title {
    font-size: 24px;
    text-decoration: none;
    color: #222831;
  }

  .articles article .media .article-title:hover {
    color: #d65a31;
  }

  .jumbotron {
    background-color: #eeeeee;
  }

  footer {
    background-color: #393e46;
    padding: 2rem;
  }
  </style>
</head>

<body style="background-color: #eeeeee;" class="text-dark">
  <header>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #393e46;">
      <a class="navbar-brand " href="{% url 'home' %}"><img src="/media/snakeWhite.png" width="32" height="32"
          class="d-inline-block align-top" alt=""></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarMenu">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articles:list' %}">NEWS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/challenges/">CHALLENGES</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="dropdown d-none d-lg-block">
          <button class="btn dropdown-toggle text-white" type="button" id="dropdownUser" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <img src="/media/userWhite.png" width="24" height="24" class="d-inline-block align-top mx-1" alt="">
            <span class="text-uppercase">{{ user.username }}</span>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUser"
            style="background-color: #393e46;">
            <a class="dropdown-item text-white" href="/accounts/">ACCOUNT</a>
            <div class="dropdown-divider"></div>
            <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <a onclick="$(this).closest('form').submit()" class="dropdown-item text-white" href="#">LOG OUT</a>
            </form>
          </div>
        </div>
        <ul class="navbar-nav mr-auto d-sm-block d-lg-none">
          <a class="nav-link" href="/accounts/">ACCOUNT</a>
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <a onclick="$(this).closest('form').submit()" class="nav-link" href="#">LOG OUT</a>
          </form>
        </ul>
        {% else %}
        <button class="btn btn-danger mx-1 d-none d-lg-block" type="button" style="width: 120px;"
          onclick="window.location.href='{% url 'accounts:login' %}'">LOG IN</button>
        <ul class="navbar-nav mr-auto d-sm-block d-lg-none">
          <a class="nav-link" href="{% url 'accounts:login' %}">LOG IN</a>
        </ul>
        {% endif %}
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock %}
  <footer>
    <div class="row text-center text-white">
      <div class="col-12">
        <h5 class="font-weight-light">&copy; Dawid Machoczek 2020</h5>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>

templates/homepage.html
{% extends 'baseTemplate.html' %}

{% block content %}
<div class="homepage-box text-white">
    <div class="homepage-box-text text-center mx-2">
        <h1 class="display-4">WELCOME TO CODERS</h1>
        <h3>“Experience is the name everyone gives to their mistakes.” – Oscar Wilde</h3>
    </div>
</div>
<div class="container">
    <div class="jumbotron text-justify">
        <h1 class="display-4">Who are we?</h1>
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci in ipsam sit ducimus vitae
            quidem qui natus architecto delectus, est quae quis, at molestiae exercitationem, nihil explicabo laudantium
            fugiat nam distinctio laboriosam perspiciatis quaerat impedit!</p>
        <hr class="my-4">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, sunt.</p>
        <p class="lead">
            {% if user.is_authenticated %}
            <a href="{% url 'home' %}" class="btn btn-danger btn-lg my-2">JOIN US</a>
            {% else %}
            <a href="{% url 'accounts:signup' %}" class="btn btn-danger btn-lg my-2">JOIN US</a>
            {% endif %}
        </p>
    </div>
    <section class="coding-languages my-5">
        <div class="row text-center my-5">
            <div class="col-12">
                <h1 class="display-4">COMMON CODING LANGUAGES</h1>
            </div>
            <hr>
        </div>
        <div class="row text-center my-5">
            <div class="col-md-3 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center my-2" src="/media/pythonIcon.png" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h4 class="card-title">PYTHON</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center my-2" src="/media/vue.png" width="200px" height="200px">
                    <div class="card-body">
                        <h4 class="card-title">VUE.JS</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center my-2" src="/media/cppIcon.png" width="200px" height="200px">
                    <div class="card-body">
                        <h4 class="card-title">C++</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-3 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center my-2" src="/media/angular.png" width="200px" height="200px">
                    <div class="card-body">
                        <h4 class="card-title">ANGULAR</h4>
                    </div>
                </div>
            </div>
    </section>
    <div class="row my-5">
        <div class="col-lg-6">
            <h2 class="display-4">OUR DESTINATION</h2>
            <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis inventore aliquam eum,
                reprehenderit quo corrupti deserunt maxime unde consectetur asperiores odio cupiditate veniam pariatur
                voluptatum facilis laudantium. Error odit nihil ut voluptatibus impedit? Modi reiciendis dolorum
                temporibus illum doloribus laudantium corrupti iure, molestias nesciunt, commodi vitae eos dicta quasi
                in incidunt, magnam velit hic est.</p>
            <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus itaque quasi cum
                voluptatem ullam
                aliquid nemo eveniet! Eos perferendis voluptates deleniti voluptate dolores aspernatur error?</p>
            <br />
        </div>
        <div class="col-lg-6 align-self-center">
            <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="/media/defaultImage.jpg" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="/media/defaultImage.jpg" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="/media/defaultImage.jpg" class="d-block w-100" alt="...">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </div>
    </div>
    <section class="text-editors my-5">
        <div class="row text-center my-5">
            <div class="col-12">
                <h1 class="display-4">COMMON TEXT EDITORS</h1>
            </div>
            <hr>
            <div class="col-12">
                <p class="lead">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Assumenda officia ratione
                    laborum
                    dolore minima distinctio cupiditate nulla facilis. Nulla, delectus reprehenderit iste quia
                    temporibus a
                    assumenda repellat excepturi facilis ipsa? Veritatis, numquam eum? Dignissimos velit magni magnam
                    iste
                    debitis ipsam. Quibusdam consequatur culpa itaque voluptatem?</p>
            </div>
        </div>
        <div class="row text-center my-5">
            <div class="col-md-4 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center" src="/media/visualStudio.png" width="256px" height="256px">
                    <div class="card-body">
                        <h4 class="card-title">Visual Studio Code</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde, architecto,
                            cumque atque rerum aperiam repellat soluta error tempora velit labore, nostrum quia
                            recusandae
                            vitae dolor! Impedit ducimus, atque ullam consectetur molestiae eius nesciunt minima quidem?
                        </p>
                        <a href="#" class="btn btn-danger btn-block">DOWNLOAD</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center" src="/media/atom.png" width="256px" height="256px">
                    <div class="card-body">
                        <h4 class="card-title">Atom</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum ab
                            error
                            animi iure, dolor reiciendis nisi voluptatibus temporibus provident excepturi tempora libero
                            nesciunt ullam nobis voluptates facere iusto rerum aperiam ipsum eius? Natus, obcaecati
                            labore.
                        </p>
                        <a href="#" class="btn btn-danger btn-block">DOWNLOAD</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 my-2">
                <div class="card">
                    <img class="img-fluid align-self-center" src="/media/sublimeText.png" width="256px" height="256px">
                    <div class="card-body">
                        <h4 class="card-title">Sublime Text</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore facilis
                            deserunt aspernatur facere quos atque culpa illum quo porro aliquid animi corrupti sit
                            consequatur, numquam aliquam, fuga voluptate? Laboriosam ea numquam dolores quasi,
                            exercitationem illum!</p>
                        <a href="#" class="btn btn-danger btn-block">DOWNLOAD</a>
                    </div>
                </div>
            </div>
    </section>
</div>


{% endblock %}